<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <Authors>Marcus V. Freitas</Authors>
    <Company>MVFC</Company>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Marcus-V-Freitas/MVFC.Veragi.Simulator</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Veragi.Simulator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' != 'true' AND !$([System.String]::new('$(MSBuildProjectDirectory)').Contains('playground'))">
    <PackageReference Include="MinVer" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true' OR $([System.String]::new('$(MSBuildProjectDirectory)').Contains('tests')) OR $([System.String]::new('$(MSBuildProjectDirectory)').Contains('playground'))">
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
</Project>