<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>    
	  <PackageReference Include="MediatR" />
	  <PackageReference Include="FluentValidation" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="../MVFC.Veragi.Simulator.Shareable/MVFC.Veragi.Simulator.Shareable.csproj" />
	</ItemGroup>
	
</Project>
